# Jekyll
exclude: ['nbproject', 'README.md', 'manifest.yml', 'rakefile.rb', 'Gemfile', 'Gemfile.lock', 'update.sh', 'localupdate.sh','s3_website.yml']
permalink:   pretty
url:         http://www.uberobert.com

safe:        false

future:      false
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Site
uberobert:
    title: Uberobert

