# Jekyll
exclude: ['nbproject', 'README.md', 'manifest.yml', 'rakefile.rb', 'Gemfile', 'Gemfile.lock', 'update.sh', 'localupdate.sh','s3_website.yml']
permalink:   /:title
url:         http://www.uberobert.com

safe:        false

future:      false
markdown: kramdown
highlighter: rouge

# Site
uberobert:
    title: Uberobert

# Only First P Plugin
only_first_p:
    show_read_more_link: false
